In [2]:
import pandas as pd
from scipy.stats import f_oneway

In [3]:
df = pd.read_excel('D:/Madhubalaji/Probability/Anova_dataset.xlsx')

In [4]:
df.head(20)

    Machine  Measurement
0         1           18
1         1           17
2         1           16
3         1           19
4         2           16
5         2           19
6         2           18
7         2           15
8         3           20
9         3           16
10        3           18
11        3           19
12        4           15
13        4           17
14        4           21
15        4           19
16        5           18
17        5           19
18        5           17
19        5           21

In [5]:
print(df.columns)

Index(['Machine', 'Measurement'], dtype='object')

In [6]:
Measurement = df['Measurement']
Machine_number = df["Machine"]

In [7]:
grouped_data = [Measurement[Machine_number == i] for i in range (1,7)]

In [8]:
print(grouped_data)

[0    18
1    17
2    16
3    19
Name: Measurement, dtype: int64, 4    16
5    19
6    18
7    15
Name: Measurement, dtype: int64, 8     20
9     16
10    18
11    19
Name: Measurement, dtype: int64, 12    15
13    17
14    21
15    19
Name: Measurement, dtype: int64, 16    18
17    19
18    17
19    21
Name: Measurement, dtype: int64, 20    18
21    16
22    18
23    20
Name: Measurement, dtype: int64]

In [9]:
f_statistic, p_value = f_oneway(*grouped_data)

In [10]:
alpha =0.5

In [11]:
if p_value < alpha:
    print("Mean tesnsile strengths signficantly differ for six machine(Reject null hypothesis)")
else:
    print("Mean tensile strengths do not differ significantly for the six machines (Fail to reject null hypothesis)")

Mean tensile strengths do not differ significantly for the six machines (Fail to reject null hypothesis)

In [14]:
df_b = pd.read_excel('D:/Madhubalaji/Probability/Anova_dataset.xlsx', sheet_name = "Part B")

In [20]:
df_b.head(100)

    Solvent  Samples
0         1     1.06
1         1     0.79
2         1     0.82
3         1     0.89
4         1     1.05
5         1     0.95
6         1     0.65
7         1     1.15
8         1     1.12
9         2     1.58
10        2     1.45
11        2     0.57
12        2     1.16
13        2     1.12
14        2     0.91
15        2     0.83
16        2     0.43
17        3     0.29
18        3     0.06
19        3     0.44
20        3     0.55
21        3     0.61
22        3     0.43
23        3     0.51
24        3     0.10
25        3     0.53
26        3     0.34
27        3     0.06
28        3     0.09
29        3     0.17
30        3     0.17
31        3     0.60

In [15]:
print(df_b.columns)

Index(['Solvent', 'Samples'], dtype='object')

In [16]:
sorption_rates = df_b['Samples']

In [17]:
solvent_type = df_b['Solvent']

In [25]:
Grouped_data_b = [sorption_rates[solvent_type == i] for i in df_b['Solvent'].unique()]

In [27]:
print(Grouped_data_b)

[0    1.06
1    0.79
2    0.82
3    0.89
4    1.05
5    0.95
6    0.65
7    1.15
8    1.12
Name: Samples, dtype: float64, 9     1.58
10    1.45
11    0.57
12    1.16
13    1.12
14    0.91
15    0.83
16    0.43
Name: Samples, dtype: float64, 17    0.29
18    0.06
19    0.44
20    0.55
21    0.61
22    0.43
23    0.51
24    0.10
25    0.53
26    0.34
27    0.06
28    0.09
29    0.17
30    0.17
31    0.60
Name: Samples, dtype: float64]

In [31]:
f_statistic_b, p_value_b = f_oneway(*Grouped_data_b)
print(p_value_b)

5.855201452781716e-07

In [30]:
if p_value_b < alpha:
    print("There is significant difference in mean sorption rates of three solvents(reject null hypothesis)")
else:
    print("There is significant difference in mean sorption rates of three solvents(Fail to reject null hypothesis)")

There is significant difference in mean sorption rates of three solvents(reject null hypothesis)